name: Fetch HTML Data
on: workflow_dispatch
jobs:
  fetch-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch HTML Data
        run: |
          # Use curl to fetch HTML content
          curl -o output.html https://example.com

      - name: Display HTML Content
        run: |
          # Display the fetched HTML
          cat output.html
